# Generated by Django 5.0.6 on 2024-05-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
