# Generated by Django 5.0.6 on 2024-05-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_note_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
