# Generated by Django 5.0.6 on 2024-05-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_remove_note_author_notebook_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='page',
            field=models.ForeignKey(default='e9db9959-4d66-4f66-83a2-5c1436b38e9e', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='editor.page'),
            preserve_default=False,
        ),
    ]
