# Generated by Django 5.0.6 on 2024-05-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_alter_note_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='slug',
        ),
    ]
