# Generated by Django 5.0.6 on 2024-05-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_remove_notebook_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
