# Generated by Django 5.0.6 on 2024-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_alter_note_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
