# Generated by Django 5.0.6 on 2024-05-29 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0017_alter_note_options_note_editor_note_order_996d79_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='easiness_factor',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='note',
            name='inter_repetition_interval',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='note',
            name='repetition_number',
            field=models.IntegerField(default=0),
        ),
    ]
