# Generated by Django 5.0.6 on 2024-05-29 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0018_note_easiness_factor_note_inter_repetition_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_review',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 11, 9, 10, 702522)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 11, 9, 21, 493140)),
            preserve_default=False,
        ),
    ]
