# Generated by Django 5.0.6 on 2024-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0019_note_last_review_note_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_review',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='next_review',
            field=models.DateTimeField(null=True),
        ),
    ]
